apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "cluster-queue-ks"
spec:
  namespaceSelector: {} # match all.
  resourceGroups:
#  - coveredResources: ["cpu", "memory", "nvidia.com/gpu"]
  - coveredResources: ["cpu", "memory"]
    flavors:
    - name: "spot"
      resources:
      - name: "cpu"
        nominalQuota: 0
      - name: "memory"
        nominalQuota: 0Gi
    
    - name: "default-flavor"
      resources:
      - name: "cpu"
        nominalQuota: 9
      - name: "memory"
        nominalQuota: 4Gi

  admissionChecks:
  - kubestellar-admc