# permissions for end users to view clustermetrics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clustermetrics
    app.kubernetes.io/managed-by: kustomize
  name: clustermetrics-viewer-role
rules:
- apiGroups:
  - galaxy.kubestellar.io
  resources:
  - clustermetrics
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - galaxy.kubestellar.io
  resources:
  - clustermetrics/status
  verbs:
  - get
